### ISSUE TITLE
doubt in class prediction

### ISSUE THREAD

**Issue by gauravjain10** [ZhiyuanDang/NNM#4]
hi @ZhiyuanDang 
One doubt I have now is where are you getting the templates from ? By template I mean what you are using to find Nearest Neighbour?
Is it like you have a set of examples (templates) for each class, and you are computing distance between candidate images with those templates to label the test images ?
I am really interested in the area of unsupervised image classification and this paper is trying to solve this problem.Please try to help me to clear my doubt.
Another doubt what kind of issues you are facing in self-label script.

**Comment by ZhiyuanDang** [comment]
Please see the code (line 90 in utils/train_utils.py). We use larger L2-similarity to determine the Nearest Neighbour. 

Sometimes, the self-label script may cause performance degernration. You can check the issues in SCAN work.

**Comment by gauravjain10** [comment]
hi @ZhiyuanDang,

I will take a look in train_utils.py Thank you so much.
