### ISSUE TITLE
pretrain model

### ISSUE THREAD

**Issue by haoweiclouds1** [ZhiyuanDang/NNM#7]
dear zhiyuan dang ,
i find i can't download ,
can you provide pretrain model pth.tar ,please

thank you very much

![QQ截图20211215191204](https://user-images.githubusercontent.com/91071905/146176571-941c33f4-cef3-49ce-b543-2d8fbf026d39.png)

**Comment by haoweiclouds1** [comment]
![QQ截图20211215191204](https://user-images.githubusercontent.com/91071905/146176415-988bb015-786d-4efc-af71-2ad173b20161.png)

cannot download since yesterday

**Comment by ZhiyuanDang** [comment]
Oh, you mean that the SCAN pre-trained models? Fine, I will upload them ASAP.

**Comment by ZhiyuanDang** [comment]
I have uploaded the pre-trained models.

**Comment by haoweiclouds1** [comment]
thank you， i got it！
